import {
  Image1,
  Image2,
  Image3,
  Image4,
  Image5,
  Image6,
  Image7,
  Image8,
  Image9,
} from "../../assets/images/image";

export const cards = [
  {
    id: 1,
    image: Image1,
    title: "Barberton Daisy",
    price: 119.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 2,
    image: Image2,
    title: "Angel Wing Begonia",
    price: 169.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 3,
    image: Image3,
    title: "African Violet",
    price: 199.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 4,
    image: Image4,
    title: "Beach Spider Lily",
    price: 129.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 5,
    image: Image5,
    title: "Blushing Bromeliad",
    price: 139.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 6,
    image: Image6,
    title: "Aluminum Plant",
    price: 179.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 7,
    image: Image7,
    title: "Bird's Nest Fern",
    price: 99.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 8,
    image: Image8,
    title: "Broadleaf Lady Palm",
    price: 59.0,
    isFavorite: false,
    isBasket: false,
  },
  {
    id: 9,
    image: Image9,
    title: "Chinese Evergreen",
    price: 39.0,
    isFavorite: false,
    isBasket: false,
  },
];
